### ISSUE TITLE
Lab 1 on OCP 4.4 userX cannot create address space

### ISSUE THREAD

**Issue by evanshortiss** [RedHatWorkshops/dayinthelife-streaming#38] opened 2020-07-23 18:46 UTC
Running on OCP 4.4 the user cannot complete "7. Create your AMQ Online Topic" since they cannot view the catalog. They need "cluserservices" permissions.

**Comment by evanshortiss** [comment] 2020-07-23 18:51
Navigating to `https://$CLUSTER_HOST/catalog/ns/user1` results in an error or blank page. Web inspector reveals 403 HTTP response from `https://$CLUSTER_HOST/api/kubernetes/apis/config.openshift.io/v1/clusterversions/version` and 404 from https://$CLUSTER_HOST/api/kubernetes/api/v1/namespaces/openshift-logging/configmaps/sharing-config`

**Comment by evanshortiss** [comment] 2020-07-23 18:58
* `/api/kubernetes/apis/ocs.openshift.io/v1/namespaces/openshift-storage/storageclusters/ocs-independent-storagecluster` - 403
* `/api/kubernetes/apis/operators.coreos.com/v1alpha1/namespaces/openshift-storage/subscriptions/ocs-subscription` - 404
* `api/kubernetes/apis/config.openshift.io/v1/infrastructures/cluster` - 403
* `/api/kubernetes/apis/apiregistration.k8s.io/v1/apiservices?` - 403

**Comment by evanshortiss** [comment] 2020-07-23 19:00
Even after adding full cluster-admin rights (`oc adm policy add-cluster-role-to-user cluster-admin user1`) the user cannot view the catalog. Might be an issue with this cluster?

**Comment by sigreen** [comment] 2020-07-23 20:47
I had the same issue with two separate workshops today on RHPDS @evanshortiss .  Work around is to naviagate to the Administrator Console, select the Operator and create the Address Space that way.  Unfortunately this didn't work for Postgres lab as there is no operator available.

**Comment by dgutride** [comment] 2020-07-24 10:20
I also had this issue - it's a missing a displayName in the Infinispan Operator for the Cache - once that was added in the yaml for the operator, the Catalog page was visible.  This is because the tileName is undefined.

**Comment by evanshortiss** [comment] 2020-07-24 10:42
Nice find @dgutride! So do we know if this is isolated to OCP 4.4 or is it an issue with the pre-created Infinispan operator that can be addressed in the installer, or perhaps caused by a mixture of hte two?

**Comment by dgutride** [comment] 2020-07-24 11:23
@evanshortiss  - the code is the same between minor versions of OpenShift - I upgraded to try to fix this in the process.  I'm not quite sure why they aren't validating the displayName on the operator yaml unless the install process here is doing something unusual.

I think the issue is with infinispan - looks like this commit broke things a few weeks ago:  https://github.com/infinispan/infinispan-operator/commit/20e7885ad913b73f1d8f5befcbf0f7b635169fcb#diff-350feddf31ee00a2f0bcf71b204a30c1.   

Created this PR: https://github.com/infinispan/infinispan-operator/pull/485 to see if they'll take it in for the issue.

**Comment by evanshortiss** [comment] 2020-07-24 13:59
@sigreen looks like that'll do the trick 👍 

@dgutride I just checked and the `displayName` is there on my cluster. So maybe there's another issue at play here?

<img width="1645" alt="Screenshot 2020-07-24 at 2 57 10 PM" src="https://user-images.githubusercontent.com/1303687/88399015-22d3af00-cdbe-11ea-8ef0-8f3844e3b9e8.png">

**Comment by dgutride** [comment] 2020-07-24 14:10
@evanshortiss  - you need another displayName entry for the cache (line 60 or so)

**Comment by sigreen** [comment] 2020-07-24 15:49
Thanks @dgutride and @evanshortiss . I can confirm that Dana's fix has resolve my issue. I updated the Infinispan operator YAML in userX project at line 55 to the following:

```
spec:
  customresourcedefinitions:
    owned:
      - description: Cache is the Schema for the caches API
        displayName: Infinispan Cache
        kind: Cache
        name: caches.infinispan.org
        version: v2alpha1
      - description: An Infinispan cluster instance.
        displayName: Infinispan Cluster
        kind: Infinispan
        name: infinispans.infinispan.org
```
After saving that change, I was able to login to my user project and view the catalog!

**Comment by evanshortiss** [comment] 2020-07-27 12:30
Thanks @dgutride, and @sigreen

**Comment by hguerrero** [comment] 2020-08-07 21:38
This should have been fixed by the change to Data Grid instead.

**Closed by hguerrero** 2020-08-07 21:38 UTC
Labels: bug
